### PR TITLE
Use company name in identifier

### PR DESCRIPTION
**Pull request by codeabit**
Use company name supplied by user during bootstrap for creating unique Add-on identifier.

NO-CRAB.

### CODE REVIEW

**Review by nanophd — APPROVED** [review]
Exploratory Testing Notes:
Didn't test, but looks good.

Good catch.

**Review by monstrorivas — COMMENTED** [review]
Looks good but haven't tested yet. I can test on Monday but I'm OK if this gets merged before.

**Comment by monstrorivas** [comment]
Exploratory testing notes: 

✅ Pulled this branch and installed the updated utility
✅ Created new project with `addon create <project_name>`
✅ `Enter the name of your company` appeared as one of the prompts
✅ The company name was used to create the identifier and used in the addon.json and the plugins and add-on tool example
🟡 If I entered `Acme Inc.` as the name of the company the identifier will show as `com.acme_inc..add-on-name` (two dots). I don't think it's a big deal, we can build and deploy, just a little weird to the developer.
✅ Bootstrapped, built and deployed the package add-on

**Review by monstrorivas — APPROVED** [review]

**Comment by codeabit** [comment]
> If I entered `Acme Inc.` as the name of the company the identifier will show as `com.acme_inc..add-on-name` (two dots). I don't think it's a big deal, we can build and deploy, just a little weird to the developer.

I agree the identifier looks a bit odd with two dots and also that it's not a big deal. IMO it'll probably be less surprising to see the extra dot(s) from the specified company name in the identifier than it would be if we were to trim leading/trailing dots.

**Pull request merged**
